# Generated by Django 5.0.2 on 2024-02-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
    ]
