# Generated by Django 5.0.2 on 2024-04-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
