# Generated by Django 5.0.2 on 2024-02-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_usuario_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='en_pretsamo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
