# Generated by Django 5.0.2 on 2024-04-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_transacciones_fecha_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='fecha_estimada',
            field=models.DateField(),
        ),
    ]
