# Generated by Django 5.0.2 on 2024-02-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_initial'),
    ]

    operations = [
    ]
