# Generated by Django 5.0.2 on 2024-02-22 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_inventario_en_pretsamo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='en_pretsamo',
            new_name='en_prestamo',
        ),
    ]
