# Generated by Django 5.0.2 on 2024-02-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_en_pretsamo_inventario_en_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='en_prestamo',
            field=models.BooleanField(default=False),
        ),
    ]
