# Generated by Django 5.0.2 on 2024-02-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20240226_1431'),
    ]

    operations = [
    ]
